### ISSUE TITLE
Restart loop on `flyctl deploy`

### ISSUE THREAD

**Issue by sloane-shark** [fly-apps/docker-daemon#1]
I'm using the repo roughly as-is and trying to launch the docker daemon. The app starts up, but then seems to immediately shut down:

```bash
2022-08-27T02:31:30.489 app[c5cddc15] ewr [info] Running dockerd -p /var/run/docker.pid
2022-08-27T02:31:31.448 app[c5cddc15] ewr [info] Starting clean up.
2022-08-27T02:31:31.463 app[c5cddc15] ewr [info] Umounting /dev/vdc from /data 
```

Should any changes be necessary to get this working? I'm attempting to try this out with pretty small resource allocations, could that be part of the issue?

**Comment by sloane-shark** [comment]
This fork seems to have a configuration that works out of the box for me: https://github.com/kotx/docker-daemon

**Comment by bilby91** [comment]
@matthewess I'm having the same issue that you mentioned. I tried kotx fork but the app doesn't start at all in this case. It's in an "Error" state and I don't see any output in the logs.

Did you manage to get it working ? Are you currently using it ?

**Comment by sloane-shark** [comment]
I used it for awhile but haven't been running it recently. I think last I checked, it worked for me as-is

**Comment by sloane-shark** [comment]
@bilby91 recommend starting a thread on community.fly.io for better assistance

**Comment by bcjordan** [comment]
Came across this repo and the fix mentioned by Matthew in that repo appeared to work - would it make sense to merge that `Dockerfile` change in to this repo? Or to archive it and point to Apps v2/Machines or that repo? Would have saved me a bit of searching

**Comment by bcjordan** [comment]
lol I managed to run in to the issue again and forget I had been through this before, hello me 😆
